import { ReactNode } from 'react'
import './globals.css'
import ThemeProvider from './themeProvider'
// import localFont from 'next/font/local' -> lib for implementing local fonts

// local custom-font
// const graphieFont = localFont({
//   src: [
//     {
//       path: '../../public/fonts/Graphie/Graphie-Light.otf',
//       style: 'normal',
//       weight: '300',
//     },
//     {
//       path: '../../public/fonts/Graphie/Graphie-Regular.otf',
//       style: 'normal',
//       weight: '400',
//     },
//     {
//       path: '../../public/fonts/Graphie/Graphie-SemiBold.otf',
//       style: 'normal',
//       weight: '600',
//     },
//     {
//       path: '../../public/fonts/Graphie/Graphie-Bold.otf',
//       style: 'normal',
//       weight: '700',
//     },
//   ],
//   variable: '--font-graphie',
//   display: 'swap',
// })

// const terminaFont = localFont({
//   src: [
//     {
//       path: '../../public/fonts/Termina/Termina-Light.otf',
//       style: 'normal',
//       weight: '300',
//     },
//     {
//       path: '../../public/fonts/Termina/Termina-Regular.otf',
//       style: 'normal',
//       weight: '400',
//     },
//     {
//       path: '../../public/fonts/Termina/Termina-Demi.otf',
//       style: 'normal',
//       weight: '600',
//     },
//     {
//       path: '../../public/fonts/Termina/Termina-Bold.otf',
//       style: 'normal',
//       weight: '700',
//     },
//   ],
//   variable: '--font-termina',
//   display: 'swap',
// })

export const metadata = {
  title: 'Next.js + Tailwind Starter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
      // className={`font-sans  ${graphieFont.variable} ${terminaFont.variable}`} -> set custom font to global
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
